import { getLocale } from './i18n/i18n.svelte';

const labels = {
  workspace: ['LOCAL WORKSPACE', '本地工作空间'],
  models: ['Models / effort', '模型／推理强度'],
  title: ['Sessions', '会话'], subtitle: ['Connect usage to the work it supported.', '把用量与实际完成的工作联系起来。'],
  search: ['Search named titles, projects or session IDs', '搜索会话名、项目或 ID'], all: ['All providers', '所有提供商'],
  project: ['Project path (optional)', '项目路径（可选）'], recent: ['Recent activity', '最近活动'], tokens: ['Tokens', 'Tokens'], name: ['Named titles', '按已命名标题'],
  apply: ['Apply filters', '应用筛选'], reset: ['Reset', '重置'], previous: ['Previous', '上一页'], next: ['Next', '下一页'],
  empty: ['No sessions match these filters.', '没有符合筛选条件的会话。'], select: ['Select a session to explore its requests, usage and evidence.', '选择会话，查看需求、用量和证据。'],
  loading: ['Loading…', '加载中…'], retry: ['Retry', '重试'], refresh: ['Refresh', '刷新'], settings: ['Analysis settings', '分析设置'],
  alias: ['Local alias', '本地别名'], save: ['Save', '保存'], cancel: ['Cancel', '取消'], saved: ['Saved', '已保存'],
  native: ['Original title', '原始标题'], prompt: ['Request excerpt', '需求摘录'], fallback: ['Project / date', '项目／日期'],
  sessionId: ['Session ID', '会话 ID'], parent: ['Parent session', '父会话'], children: ['Child sessions', '子会话'],
  ownUsage: ['This session only; child usage is listed separately.', '仅此会话用量；子会话用量单独列出。'],
  calls: ['Model calls', '模型调用'], turns: ['User turns', '用户轮次'], tools: ['Tool calls', '工具调用'], failures: ['Tool failures', '工具失败'], repeated: ['Repeated tool calls', '重复工具调用'],
  cache: ['Cache read share', '缓存读取占比'], active: ['Estimated active time', '估算活跃时间'], span: ['Observed activity span', '观察到的活动跨度'],
  durationNote: ['Observed spans and capped activity gaps are estimates, not working time or generation speed.', '活动跨度与间隔封顶的活跃时间是估算值，不代表工作时间或生成速度。'],
  unknown: ['Unknown', '未知'], estimatedCost: ['Estimated API-equivalent cost', 'API 等值估算费用'],
  messages: ['Conversation', '对话'], metrics: ['Turns & tools', '轮次与工具'], evaluation: ['Assessment', '评测'],
  contentOff: ['Conversation content is off. Enable local content access to read requests and prepare assessments.', '对话内容访问已关闭。启用本地内容读取后，可查看需求和准备评测。'],
  enable: ['Enable local content', '启用本地内容读取'], contentUnavailable: ['The original transcript is unavailable.', '原始会话记录不可用。'],
  user: ['User', '用户'], assistant: ['Assistant', '助手'], tool: ['Tool', '工具'], truncated: ['Excerpt truncated', '内容已截断'], more: ['Load more messages', '加载更多消息'],
  selectedTurns: ['Selected turns', '已选轮次'], allTurns: ['No selection means all available turns.', '未选择时使用全部可用轮次。'],
  prepare: ['Prepare redacted preview', '准备脱敏预览'], preview: ['Review exactly what will be sent', '检查即将发送的确切内容'],
  previewNote: ['Edit or remove sensitive content below. Preparing a preview makes no remote request.', '可编辑或移除下方敏感内容。准备预览不会发起远程请求。'],
  send: ['Send this preview for assessment', '发送此预览并评测'], sending: ['Assessing…', '正在评测…'], stop: ['Stop waiting', '停止等待'],
  cancelled: ['Stopped waiting. The request may still finish and incur charges. Refresh reports before sending again.', '已停止等待。请求仍可能完成并产生费用，再次发送前请刷新报告。'],
  approximate: ['Approximate input tokens', '粗略输入 Tokens'], chars: ['Characters', '字符数'], maxOutput: ['Maximum output tokens', '输出 Tokens 上限'],
  budget: ['Estimated cost at output limit', '按输出上限估算费用'], coverage: ['Source coverage', '来源覆盖范围'],
  setup: ['Set a model and an environment variable containing the API key. The app never stores your key.', '请配置模型和保存 API Key 的环境变量名。应用不会保存密钥。'],
  keyNote: ['Enter the variable name, not the key. Restart the app after changing its environment. Loopback services may not require a key.', '填写环境变量名，不要填写密钥。修改环境变量后请重启应用。本地回环服务可能不需要密钥。'],
  contentEnabled: ['Allow local transcript reading', '允许读取本地对话内容'], endpoint: ['Evaluation endpoint', '评测服务地址'], model: ['Evaluation model', '评测模型'], keyEnv: ['API key environment variable', 'API Key 环境变量名'],
  inputLimit: ['Maximum input characters', '输入字符数上限'], inputRate: ['Input USD / million tokens (optional)', '输入美元／百万 Tokens（可选）'], outputRate: ['Output USD / million tokens (optional)', '输出美元／百万 Tokens（可选）'],
  privacy: ['Content stays local until you explicitly send a reviewed preview. Turning content off clears derived content caches.', '内容保留在本地，只有明确发送已检查的预览时才会上传。关闭内容读取会清理派生内容缓存。'],
  noReports: ['No assessments yet. Start with a reviewed preview.', '暂无评测报告，请先准备并检查预览。'], reports: ['Saved assessments', '历史评测'], cached: ['Reused exact preview', '复用相同预览'],
  strengths: ['Prompt strengths', '提示词优点'], gaps: ['Prompt gaps', '提示词不足'], suggestions: ['Suggestions', '改进建议'], requirements: ['Requirement evidence', '需求与证据'],
  efficiency: ['Efficiency observations', '效率观察'], limitations: ['Limitations', '局限性'],
  verified: ['Evidence supports completion', '证据支持完成'], partial: ['Partly supported', '部分支持'], unmet: ['Not met', '未完成'],
  aiNote: ['AI assessments are proposals. Confirm each requirement against the cited evidence; no universal completion percentage is inferred.', 'AI 评测只是建议判断。请结合引用证据逐项确认，不推断统一的完成百分比。'],
  confirmed: ['Confirmed by me', '我已确认'], saveReview: ['Save my review', '保存我的复核'], evidence: ['Evidence', '证据'], evidenceMissing: ['Evidence is not in the loaded messages. Load earlier pages to inspect it.', '证据尚未加载，请加载更多消息后查看。'],
  proposed: ['AI proposal · unconfirmed', 'AI 建议 · 未确认'], humanReview: ['User reviewed', '用户已复核'], reviewNote: ['My review notes', '我的复核说明'],
  reviewChanged: ['Editing the status or rationale records this as your review.', '修改状态或说明后，此判断将标记为你的复核。'],
  clear: ['Clear this session’s analysis', '清除此会话分析'], clearNote: ['Removes saved assessments and local alias. Original logs and token history remain.', '删除评测报告和本地别名，保留原始日志和 Tokens 历史。'], confirmClear: ['Confirm clear', '确认清除'],
  sourceStale: ['The source has changed since this assessment.', '此评测之后源会话已更新。'], from: ['From', '开始'], to: ['Through', '结束'],
  elapsed: ['Observed duration', '观察耗时'], noTurns: ['This log does not expose reliable turn linkage.', '此日志未提供可靠的轮次关联。'], reportUsage: ['Evaluator usage', '评测模型用量'],
  viewLabel: ['Sessions view', '会话视图'], browse: ['Browse', '浏览'], insights: ['Insights', '洞察'],
  insightsNote: ['Computed from usage, timing and tool metadata only; no conversation content is read, so this works with local content off. Estimated costs are API-equivalent, never an invoice.', '仅根据用量、时间与工具元数据计算，不读取对话内容，因此在关闭本地内容读取时同样可用。估算费用为 API 等值，不是账单。'],
  insightsCapped: ['Analysing the newest {shown} of {total} matching sessions.', '正在分析最近的 {shown} 个会话（共 {total} 个匹配）。'],
  insightsEmpty: ['No sessions match these filters, so there is nothing to analyse.', '没有符合筛选条件的会话，无可分析内容。'],
  kpiSessions: ['Sessions', '会话数'], kpiMedianCost: ['Median cost / session', '会话费用中位数'], kpiMedianActive: ['Median active time', '活跃时间中位数'],
  kpiMedianTurns: ['Median user turns', '用户轮次中位数'], kpiFailureRate: ['Tool failure rate', '工具失败率'], kpiRepeatRate: ['Repeated-call rate', '重复调用率'],
  kpiPriced: ['{n} priced', '{n} 个有价格'], kpiOfCalls: ['{n} of {total} calls', '{n} / {total} 次调用'],
  costDist: ['Cost per session', '每会话费用分布'], durationDist: ['Active time per session', '每会话活跃时间分布'],
  distNote: ['Log-scale bins, three per decade. Sessions with zero value are not drawn.', '对数分箱，每十倍三档；数值为零的会话不绘制。'],
  sessionsAxis: ['Sessions', '会话数'], median: ['Median', '中位数'], p90: ['P90', 'P90'], bin: ['Range', '区间'], zeroSessions: ['at zero', '为零'],
  scatterTitle: ['Turns vs. cost', '轮次与费用'], scatterNote: ['Point size is tool failures, colour is provider. Select a point to open the session.', '点大小表示工具失败数，颜色表示服务商。选择一个点即可打开会话。'],
  turnsAxis: ['User turns', '用户轮次'], costAxis: ['Estimated cost (USD)', '估算费用（美元）'], scatterUnpriced: ['{n} sessions without a known price are not plotted.', '{n} 个价格未知的会话未绘制。'],
  topCost: ['Most expensive sessions', '费用最高的会话'], topDuration: ['Longest sessions', '最长的会话'], topFailures: ['Highest tool-failure rate', '工具失败率最高'], topRepeats: ['Most repeated tool calls', '重复工具调用最多'],
  topNone: ['Nothing to show.', '暂无内容。'], failureRateShort: ['failure rate', '失败率'], repeatsShort: ['repeated', '重复'],
  flagFailures: ['High failure rate', '失败率偏高'], flagRepeats: ['Many repeated calls', '重复调用偏多'],
  whyFailures: ['Failed tool calls are usually retried, which adds turns and tokens without moving the task forward. Flagged at {n}+ failures and {p}% or more of calls.', '失败的工具调用通常会被重试，增加轮次和 Tokens 却无助于推进任务。标记条件：失败至少 {n} 次且占调用的 {p}% 以上。'],
  whyRepeats: ['Repeating the same call with identical input often points to a loop or a missing instruction; a clearer prompt or stopping earlier can save tokens. Flagged at {n}+ repeats and {p}% or more of calls.', '以相同输入重复同一调用，常说明陷入循环或缺少明确指示；更清晰的提示或更早停止可节省 Tokens。标记条件：重复至少 {n} 次且占调用的 {p}% 以上。'],
  openSession: ['Open session', '打开会话'], backToList: ['Back to insights', '返回洞察'],
  toolsTitle: ['Tool usage', '工具使用'], toolName: ['Tool', '工具'], toolCalls: ['Calls', '调用次数'], toolFailRate: ['Failure rate', '失败率'], toolSessions: ['Sessions', '会话数'],
  toolsNone: ['No tool metadata is indexed for these sessions.', '这些会话没有已索引的工具元数据。'],
} as const;
export type SessionLabel = keyof typeof labels;
export function st(key: SessionLabel, values?: Record<string, string | number>) {
  const text: string = labels[key][getLocale() === 'zh-CN' ? 1 : 0];
  return values ? text.replace(/\{(\w+)\}/g, (m, k) => (k in values ? String(values[k]) : m)) : text;
}
