#!/usr/bin/env python3
"""Render the package-manager manifests for one release (stdlib only).

    scripts/gen-packaging.py --tag v0.6.0 --assets DIR --out OUT [--release-date YYYY-MM-DD]

DIR must hold the published release assets (the .deb, both .dmg, the
-setup.exe and the .msi). SHA-256 values are computed from those files, so what
is rendered is what users will download. LICENSE is read from DIR/LICENSE when
present, otherwise fetched from the tag on GitHub (the AUR package lists it as
a source).

Templates live in packaging/ (*.in, with @@PLACEHOLDER@@ markers). Output:

    OUT/winget/<version>/*.yaml
    OUT/homebrew/ai-usage-sidebar.rb
    OUT/scoop/ai-usage-sidebar.json
    OUT/aur/ai-usage-sidebar-bin/PKGBUILD      (.SRCINFO is generated by
                                                makepkg --printsrcinfo in CI)

Every output is LF-terminated regardless of the host OS.
"""
import argparse
import datetime
import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = "harveyxiacn/AI-usage-monitor-sidebar"
TAG_RE = re.compile(r"^v(\d+\.\d+\.\d+)$")
ROOT = Path(__file__).resolve().parent.parent


def asset_names(v):
    # GitHub turns the spaces of "AI Usage Sidebar" into dots.
    return {
        "NSIS": f"AI.Usage.Sidebar_{v}_x64-setup.exe",
        "MSI": f"AI.Usage.Sidebar_{v}_x64_en-US.msi",
        "DMG_ARM": f"AI.Usage.Sidebar_{v}_aarch64.dmg",
        "DMG_X64": f"AI.Usage.Sidebar_{v}_x64.dmg",
        "DEB": f"AI.Usage.Sidebar_{v}_amd64.deb",
    }


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def license_digest(assets, tag):
    local = assets / "LICENSE"
    if local.is_file():
        return sha256_file(local)
    url = f"https://raw.githubusercontent.com/{REPO}/{tag}/LICENSE"
    with urllib.request.urlopen(url, timeout=60) as r:  # noqa: S310 (fixed https URL)
        return hashlib.sha256(r.read()).hexdigest()


def render(text, values, name):
    out = re.sub(r"@@([A-Z0-9_]+)@@", lambda m: values[m.group(1)] if m.group(1) in values else m.group(0), text)
    left = sorted(set(re.findall(r"@@[A-Z0-9_]+@@", out)))
    if left:
        sys.exit(f"{name}: unresolved placeholders {left}")
    return out


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.replace("\r\n", "\n").encode("utf-8"))
    print(f"wrote {path}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tag", required=True, help="release tag, e.g. v0.6.0")
    ap.add_argument("--assets", required=True, type=Path, help="directory with the downloaded release assets")
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--release-date", help="YYYY-MM-DD (default: today, UTC)")
    ap.add_argument("--templates", type=Path, default=ROOT / "packaging")
    a = ap.parse_args()

    m = TAG_RE.match(a.tag)
    if not m:
        sys.exit(f"tag must look like v1.2.3 (pre-release tags are not distributed): {a.tag}")
    version = m.group(1)
    date = a.release_date or datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
        sys.exit("--release-date must be YYYY-MM-DD")

    values = {"VERSION": version, "TAG": a.tag, "RELEASE_DATE": date}
    for key, name in asset_names(version).items():
        f = a.assets / name
        if not f.is_file():
            sys.exit(f"missing release asset: {f}")
        digest = sha256_file(f)
        values[f"SHA256_{key}"] = digest
        values[f"SHA256_UPPER_{key}"] = digest.upper()
    values["SHA256_LICENSE"] = license_digest(a.assets, a.tag)

    t = a.templates
    for src in sorted((t / "winget" / "templates").glob("*.yaml.in")):
        write(a.out / "winget" / version / src.name[:-3], render(src.read_text(encoding="utf-8"), values, src.name))
    write(a.out / "homebrew" / "ai-usage-sidebar.rb",
          render((t / "homebrew" / "ai-usage-sidebar.rb.in").read_text(encoding="utf-8"), values, "homebrew"))
    scoop = render((t / "scoop" / "ai-usage-sidebar.json.in").read_text(encoding="utf-8"), values, "scoop")
    json.loads(scoop)  # must be valid JSON
    write(a.out / "scoop" / "ai-usage-sidebar.json", scoop)
    write(a.out / "aur" / "ai-usage-sidebar-bin" / "PKGBUILD",
          render((t / "aur" / "ai-usage-sidebar-bin" / "PKGBUILD.in").read_text(encoding="utf-8"), values, "aur"))


if __name__ == "__main__":
    main()
